name: "Deploy"

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload
        uses: azure/CLI@v1
        with:
          azcliversion: 2.21.0
          inlineScript: |
            az storage blob sync --account-name sta2b --container '$web' --source build
      - name: Logout
        run: |
          az logout
